### ISSUE TITLE
Theme Pack Themes should be Table instead of List Reference

### ISSUE THREAD

**Issue by hengsin** [anozimada/idempiere-themepack#2]
It would be a lot more flexible to use table instead of List Reference for "Theme Pack Themes" entries. Would make it a lot easier for other bundle/plugin to add new theme too, the plugin just needs to add new record to the "Theme Pack Themes" table (Perhaps there's one or 2 more field needed for such flexbility but with Table, it will be straightforward to add whatever field necessary).

**Comment by anozimada** [comment]
Can't the other bundle/plugin just create a new AD_Ref_List  record under the "Theme Pack Themes" instead? Currently I only use it to store the name of the themes so I thought using List Reference is enough and keep it simple.
Also what fields do you need in that new table?
